const CATEGORY = {
  CATEGORY_GET: "CATEGORY_GET",
  CATEGORY_GET_SUCCESS: "CATEGORY_GET_SUCCESS",
  CATEGORY_GET_FAILED: "CATEGORY_GET_FAILED",
  CATEGORY_POST: "CATEGORY_POST",
  CATEGORY_POST_SUCCESS: "CATEGORY_POST_SUCCESS",
  CATEGORY_POST_FAILED: "CATEGORY_POST_FAILED",
  CATEGORY_PASS: "CATEGORY_PASS",
  CATEGORY_PASS_SUCCESS: "CATEGORY_PASS_SUCCESS",
  CATEGORY_PASS_FAILED: "CATEGORY_PASS_FAILED",
};

export default CATEGORY;
