const VARIATION = {
  COLOR_GET: "COLOR_GET",
  COLOR_GET_SUCCESS: "COLOR_GET_SUCCESS",
  COLOR_GET_FAILED: "COLOR_GET_FAILED",
  SIZE_GET: "SIZE_GET",
  SIZE_GET_SUCCESS: "SIZE_GET_SUCCESS",
  SIZE_GET_FAILED: "SIZE_GET_FAILED",
};

export default VARIATION;
