const TAG = {
  TAG_GET: "TAG_GET",
  TAG_GET_SUCCESS: "TAG_GET_SUCCESS",
  TAG_GET_FAILED: "TAG_GET_FAILED",
  TAG_PASS: "TAG_PASS",
  TAG_PASS_SUCCESS: "TAG_PASS_SUCCESS",
  TAG_PASS_FAILED: "TAG_PASS_FAILED",
};

export default TAG;
